version: '3.9'
services:
  client:
    container_name: client
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
